### ISSUE TITLE
Online-CMAQ CONUS Simulations:  Error from Missing GBBEPx Emissions

### ISSUE THREAD

**Issue by drnimbusrain** [NOAA-EMC/AQM#11]
Dear EMC and UFS/AQM Community:

The latest [Online-CMAQ workflow from Chan-Hoo](https://github.com/ufs-community/ufs-srweather-app/wiki/Air-Quality-Modeling) has an error when running the August 2019 case over CONUS domain (C775).  The GBBEPx emissions directory is not complete, and there are files that are missing:

Error opening NetCDF data set: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/emissions/GSCE/GBBEPx.in.C775/Reprocessed/20190801/Hourly_Emissions_regrid_rrfs_13km_20190801_t12z_new48_v2.nc

@JianpingHuang-NOAA

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA @chan-hoo @kaiWang-NOAA

**Comment by drnimbusrain** [comment]
From @KaiWang-NOAA:

The files were generated by Jianping using the old version of NCL regridding scripts. I'm not sure if those files are backed up by Jianping. In case no, I can help regenerate them using the new set of Python scripts. Just wanted to make sure of the time period, duration (e.g., 48 hr or 72 hr), and cycles (e.g., 00z or 12z) that you will need.

**Comment by chan-hoo** [comment]
@drnimbusrain, due to a storage issue, the directory "/scratch2/NCEPDEV/naqfc/RRFS_CMAQ/emissions/GSCE/GBBEPx.in.C775/Reprocessed" contains the data only for three days (08/05/2019-08/07/2019). If you want to run Online-CMAQ for other dates, please ask @JianpingHuang-NOAA for the data.

**Comment by JianpingHuang-NOAA** [comment]
Please use this link  on Hera 

/scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/RAVE.in.793/RAVE_RT

**Comment by drnimbusrain** [comment]
@JianpingHuang-NOAA I think the link you provide is for the larger domain, C793 emissions.  

Where are the associated 13 km regridded GBBEPx emissions for the **CONUS C775 domain**?

Also, @chan-hoo, this seems like an issue from a workflow perspective, as these emissions paths are explicitly defined in the config.yaml file for a CONUS, C775 domain.  See sample_config/config.yaml_canopy_rrfsconus13km_1day_hera

**AQM_FIRE_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/emissions/GSCE/GBBEPx.in.C775/Reprocessed**

Should this be updated in sample config files for CONUS tests, or can we link in the GBBEPx files from another location to this directory?

**Comment by JianpingHuang-NOAA** [comment]
/scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C775/Reprocessed  for CONUS domain (Hera).

**Comment by drnimbusrain** [comment]
Thank you @JianpingHuang-NOAA I will update my config.yaml for CONUS tests to represent the new location, but still seems like this should be updated in the workflow as well, @chan-hoo.

**Comment by bbakernoaa** [comment]
Perhaps we should think about doing what we did for UFS-Aerosols and moving the emission files to the fixed file location for the UFS.

**Comment by drnimbusrain** [comment]
Agree completely @bbakernoaa We cannot be expected to keep track of multiple changing fixed file locations, where a centralized location would be extremely beneficial.

**Comment by bbakernoaa** [comment]
@KaiWang-NOAA we should also think about integrating your regridding method into the workflow.  This way we don't have to store individual grids but rather just keep the RAW files and the workflow will regrid them into the current grid.  

This should be done for operational use anyway

**Comment by drnimbusrain** [comment]
@JianpingHuang-NOAA @chan-hoo  There is also an issue with the new file names in Jianping's directory, which I cannot find the correct one for a 48-hr forecast at: 
 /scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C775/Reprocessed/20190801/

Should we just use the 72-hr file in these directories?  **Hourly_Emissions_regrid_rrfs_13km_20190801_t12z_h72.nc**  

@chan-hoo   The current workflow for CONUS cases are incorrectly still looking for:
/scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C775/Reprocessed/20190801/**Hourly_Emissions_regrid_rrfs_13km_20190801_t12z_new48_v2.nc**

Current aqm.rc file suffix path:
  AQM_FIRE_FILE_SUFFIX: _new48_v2.nc

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA @chan-hoo @KaiWang-NOAA This is exactly why i suggested that we integrate this step into the workflow.  It is needed to properly be flexible outside and inside of the operational constraints

**Comment by chan-hoo** [comment]
@drnimbusrain, according to the code management standards, any personal paths are not allowed in the authoritative repo. As @bbakernoaa said, if the data are located in the centralized location (institutional directory path), I'll be able to update its path in the configuration file.

**Comment by drnimbusrain** [comment]
@chan-hoo @bbakernoaa @JianpingHuang-NOAA Seems like this is a larger issue and should be rectified ASAP to allow for a centralized location for all fix files that stay consistent throughout AQM/workflow development.  Real development by the larger group/community is near impossible at this point.

**Comment by chan-hoo** [comment]
@drnimbusrain, recently, @JianpingHuang-NOAA requested to add the cycle info to the file name like ("_t12z") in the configuration. So you should change the file names.

**Comment by bbakernoaa** [comment]
@chan-hoo I think that the real issue is that we shouldn't have fixed files for every grid/domain. This is a problem with the current development for research vs operations.  For both we need a job within the workflow to regrid (our current method) the GBBEPx/RAVE emissions to the target domain. This should be done within the workflow and point to the original files.  It keeps us all straight by doing it this way.

**Comment by drnimbusrain** [comment]
@chan-hoo That __t12z_ is already handled in create_aqm_rc_file.py:

aqm_fire_file_fn=AQM_FIRE_FILE+"_"+yyyymmdd+**"_t"+hh+"z"**+AQM_FIRE_FILE_SUFFIX

So, new config.yaml changes for CONUS 13 km domain should be the following, if these are the correct files to be pointing to from @JianpingHuang-NOAA 
AQM_FIRE_DIR: /scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C775/Reprocessed
AQM_FIRE_FILE_SUFFIX: _h72.nc

I also agree with @bbakernoaa , where these cumbersome issues could be avoided by eliminating fix files for every grid/domain.  Seems like this is something desperately needed going forward.

**Comment by chan-hoo** [comment]
@bbakernoaa, @drnimbusrain, if I get a sample script (with a sample data) for this task, I'll be able to add this regriding task to the workflow.

**Comment by bbakernoaa** [comment]
@KaiWang-NOAA @JianpingHuang-NOAA please help direct @chan-hoo for this step as it is being developed on your side.

**Comment by chan-hoo** [comment]
@drnimbusrain, for the canopy sample,   AQM_FIRE_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/emissions/GSCE/GBBEPx.in.C775/Reprocessed
  AQM_FIRE_FILE: Hourly_Emissions_regrid_rrfs_13km
  AQM_FIRE_FILE_SUFFIX: _new48_v2.nc
In the above path: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/emissions/GSCE/GBBEPx.in.C775/Reprocessed/20190805/, file name is "Hourly_Emissions_regrid_rrfs_13km_20190805_t12z_new48_v2.nc". I think @JianpingHuang-NOAA's files have a different format for your case.

**Comment by drnimbusrain** [comment]
@chan-hoo Exactly, this is an issue for the canopy sample config file now that the files have changed name and changed location.  According to @JianpingHuang-NOAA, these are the new settings for ANY CONUS 13 km run, including my canopy version:

AQM_FIRE_DIR: /scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/GBBEPx.in.C775/Reprocessed
AQM_FIRE_FILE: Hourly_Emissions_regrid_rrfs_13km
AQM_FIRE_FILE_SUFFIX: _h72.nc

Please correct me if I am wrong @JianpingHuang-NOAA, but agree with @bbakernoaa that a new direction is needed for fire emissions standards across domains.

**Comment by KaiWang-NOAA** [comment]
@drnimbusrain @bbakernoaa Thank you for bringing up the idea to integrating the fire emis regridding into the workflow. Actually this is on our to-do-list, in additional to fire emis regridding, we're also planning to update chemic IC generator and add bias-correction post-UPP into the new workflow. Anyway, I will coordinate with @JianpingHuang-NOAA and @chan-hoo on this in the near future.
