### ISSUE TITLE
Missing operational products

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/AQM#21]
Air quality operational products, such as hourly max and average surface concentrations of ozone and PM2.5, need to be output by the model.

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA DO you have any update on this issue? Thank you.

**Comment by BrianCurtis-NOAA** [comment]
Sure! We will be merging in Raffaele's PR once some testing is done. This provides a product for operational means. Then we have the option to use the pm2.5 calculation and min/max to output separately or use code i'm finishing up to send pm2.5 over to FV3 to use the functionality that is already there.

**Comment by HaixiaLiu-NOAA** [comment]
Thank you very much for your information @BrianCurtis-NOAA Is this a quick work that can be finished this week?

**Comment by BrianCurtis-NOAA** [comment]
Thats the goal. @JianpingHuang-NOAA is also working on another way to do the PM2.5 max/min just to have a couple options available.

**Comment by JianpingHuang-NOAA** [comment]
Yes, I have tested the FMS (Fire Management System) to calculate and write
out hourly-averaged O3 to a seperate chem file successfully. But the
hourly-averaged O3 was written to the mode computational grids.
