### ISSUE TITLE
Implement bias correction technique to improve O3 and PM2.5 predictions near surface

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#25]

**Comment by JianpingHuang-NOAA** [comment]
1) convert the code to vertical structures
2) included the code/scripts into the workflow

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA @Kai who is working on this issue. What is the status now? Please provide update on this issue. Thank you!

**Comment by JianpingHuang-NOAA** [comment]
Kai is working on it.  @Kai Wang - NOAA Affiliate ***@***.***>   Can
you updated the status?

**Comment by KaiWang-NOAA** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA I'm still working on getting the scripts ready for Chan-hoo to implement into SRW. It's been delayed to due to other more urgent issues related to post-UPP and UPP. The bias-correction products will rely on those issues. Hopefully I will get this part done by early next week.

**Comment by KaiWang-NOAA** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA I'm getting close (by either today or tomorrow) to get the vertical structure done for the bias-correction capability for the AQMv7.0 implementation. I will pass all the scripts to @chan-hoo soon.

**Comment by KaiWang-NOAA** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA @BrianCurtis-NOAA The scripts/codes for BC with the vertical structure have just been passed to @chan-hoo for the workflow implementation

**Comment by JianpingHuang-NOAA** [comment]
Great, thanks for the update.

**Comment by HaixiaLiu-NOAA** [comment]
Update from Chan-Hoo:

- The preliminary version will be available soon
- Kai said that some library files for the bias-correction executables should be updated. However, they were not delivered to me yet.
- Once they are updated, the executables needs to be tested again in AQM-utils
