### ISSUE TITLE
Implement cycling capability in the workflow to support operational implementation 

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#27]
To ensure forecast product deliverable on time, it is proposed to use previous cycle GFS ICs and output files to generate ICs and met LBCs for driving current cycle AQM runs. Meanwhile , previous cycle GEFS aerosol outputs are used to update aerosol LBCs.   It is required to modify the workflow to copy with this issue.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, can you explain this issue in detail with an example? In addition, can you point me to the GFS and GEFS data directories on WCOSS2 and Hera?

**Comment by JianpingHuang-NOAA** [comment]
WCOSS2:
GFS:  /lfs/h1/ops/prod/com/gfs/v16.2
GEFS:  /lfs/h1/ops/prod/com/gefs/v12.3/gefs.20221101/00/chem/sfcsig

I am not sure that we have real-time gfs and gefs/aerosol data files on
Hera.

I have scheduled a meeting with you on this issue today.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA , does it mean this capability is only for the real-time run? Don't you have any GEFS data files on Hera?

**Comment by JianpingHuang-NOAA** [comment]
@Chan-Hoo Jeon - NOAA Affiliate ***@***.***>  We need the same
capability to support the retro runs.  I have one-week GEFS/Aerosol output
files (August 1-7, 2019) on Hera
at /scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/GEFS_aerosol

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA , as cactus is on the production mode now, I don't have access to it. On WCOSS2, how many cycles per day are there in the GEFS directory? On Hera, we have only one cycle "00".

**Comment by JianpingHuang-NOAA** [comment]
@Chan-Hoo Jeon - NOAA Affiliate ***@***.***>  We only have 00z
cycle  data on Hera. This will be the same as the retro since we have only
data files at 00z.

**Comment by chan-hoo** [comment]
My question was not for Hera but for WCOSS2.

**Comment by BrianCurtis-NOAA** [comment]
Implemented in Workflow
