### ISSUE TITLE
Implement the post-UPP utility in the workflow to support operational implementation

### ISSUE THREAD

**Issue by KaiWang-NOAA** [NOAA-EMC/AQM#28]
The utility is ready for the implementation except for one issue that needs to be resolved. The issue is that the encoding of grib2 header for day-1 24-hr PM2.5 generated by the wgrib2 library cannot be recognized by the METPlus from the verification team.

The example of current header is: 
"  PRODUCT TEMPLATE 4. 8: ( PARAMETER = PMTF     0 13 193 )  13 193 2 0 89 0 0 1 -1 105 0 1 255 -127 -2147483647 2022 
8 16 4 0 0 1 0 0 2 1 **-21** 255 0
  FIELD: PMTF    1 hybrid lvl (1 -) valid  1 hour before 2022081506:00:00 to 2022081604:00:00
" 
Where the highlighted **-21** should be 23.

**Comment by HaixiaLiu-NOAA** [comment]
@KaiWang-NOAA Do you have idea who can help with fixing this issue?

**Comment by KaiWang-NOAA** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA, a lot of discussions have taken place in the past couple of weeks involving the people from EIB, VPPPGB, CPC, and NCEP lib team. I have also made a few attempts to change the encoding. I think we're closing to get a final solution here. The current plan is that I will generate one set of sample data using the time encoding of -1-22 for day1 06z cycle for the downstream user testing. The encoding has passed the METplus verification package. On the other hand, Ed from the NCEP lib team is helping to resolve a bug of g2lib and g2clib in dealing with the negative forecast hours.

**Comment by HaixiaLiu-NOAA** [comment]
@Kai Can this be closed now?

**Comment by KaiWang-NOAA** [comment]
I'm closing this issue since we decided to use the similar Fortran code of current AQMv6 to generate the products.

**Comment by KaiWang-NOAA** [comment]
@HaixiaLiu-NOAA @BrianCurtis-NOAA  Reopened since we're reusing this issue for the Fortran based post-UPP implementation. The scripts/codes have been passed from @JianpingHuang-NOAA  to @chan-hoo for the workflow implementation

**Comment by HaixiaLiu-NOAA** [comment]
Update on this issue from Chan-Hoo:

- The preliminary version of the new POST-STAT task is ready for use
- Jianping’s scripts work only with his input files (phy/dyn) which are created by his workflow
      1, This preliminary version works with his input files
      2, His change should be merged into the authoritative branch by a PR
