### ISSUE TITLE
Rerun GEFS/Aerosol v12.3 to support AQMv7.0 retro runs

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#29]
Rerun the latest GEFS/Aerosol forecast to support the AQM v7.0 retro runs.

1) Time periods:  Dec. 16, 2021 to Feb. 28, 2022;  May 16, 2022 to Oct. 1. 2022
2) Cycles and forecast hours:   00z cycle 90-hr forecast

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA Can you clarify that the rerun needs to be conducted by which team? the AQM team or someone in physics team? Thanks.

**Comment by JianpingHuang-NOAA** [comment]
You need to talk to Helin who is going to do the work

**Comment by yangfanglin** [comment]
@JianpingHuang-NOAA Jianping, can you document here why the rerun is needed and if any extra fields needed to be saved ?   I thought GEFS.v12.3 had been run for at least 2022.  @lipan-NOAA Li, were data from the retro and real-time GFS.v12.3 parallels archived ?

**Comment by lipan-NOAA** [comment]
@yangfanglin I archived data for 2022, but only for 24 hours. I think Jianping's run needs 90 hours data.

**Comment by yangfanglin** [comment]
@lipan-NOAA Li, can you estimate how much disk space is needed to save the required GEFS.v12.3 data from the reruns to support online-CMAQ retros ?   You can assume only 6 hourly forecast data are needed from the 00Z cycle,  up to 90 hours of forecast for each cycle.

**Comment by lipan-NOAA** [comment]
@yangfanglin @JianpingHuang-NOAA I will work on it

**Comment by yangfanglin** [comment]
@lipan-NOAA have you start to the retro runs ?

**Comment by lipan-NOAA** [comment]
Yes, I did. I am downloading initial conditions.

**Comment by lipan-NOAA** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA @yangfanglin @BrianCurtis-NOAA The run has started. It may take 40 days to complete all the runs.

**Comment by JianpingHuang-NOAA** [comment]
It is fine with us.

Jianping

**Comment by lipan-NOAA** [comment]
@HaixiaLiu-NOAA @yangfanglin @JianpingHuang-NOAA The retrospectives were completed. 

HPSS:/NCEPDEV/emc-naqfc/5year/Li.Pan/GSDCHEM/LBC, 

Please test it and let me know if there is a problem.

**Comment by HaixiaLiu-NOAA** [comment]
@lipan-NOAA Thank you so much.

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA Should this issue be closed?

**Comment by JianpingHuang-NOAA** [comment]
Yes.
