### ISSUE TITLE
 RAVE data transition to operation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#30]

**Comment by KaiWang-NOAA** [comment]
We will need to find a general space on both storage (for several days of data for operation) and HPSS (for long term storage) to save the RAVE data.

**Comment by BrianCurtis-NOAA** [comment]
@KaiWang-NOAA @JianpingHuang-NOAA What's the latest on this?

**Comment by KaiWang-NOAA** [comment]
@BrianCurtis-NOAA We're still waiting for the location/quota of common space to hold all the AQMv7 fixed data. The RAVE data should be part of those fixed data.

**Comment by HaixiaLiu-NOAA** [comment]
A ticket was submitted to request DataFlow to pull RAVE data from NESDIS ftp site initially and later switch to pull from the official PDA server once the RAVE becomes NESDIS operational product. Here is the ticket information.

RITM0245859: https://nsdesk.servicenowservices.com/nco?id=ticket&table=sc_req_item&sys_id=019f2da71b916550ee15a7dbe54bcb15&view=)

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA this one too

**Comment by JianpingHuang-NOAA** [comment]
Done
