### ISSUE TITLE
Restart capability of AQM

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#31]
It is required to have a restart capability of model to follow NCO EE2 compliance.

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA @chan-hoo What is the latest on this issue?

**Comment by chan-hoo** [comment]
@BrianCurtis-NOAA, unfortunately, no update so far. I was not able to start it yet. I have a question about the restart option of the ufs weather model. Do you know if it works for the coupled case like Online-CMAQ (atm+aqm) too?

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA I am closing this one since this issue has been replaced by the issue #71
