### ISSUE TITLE
NEXUS failed with SRW workflow on Hera

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#33]
NEXUS failed to run with the latest SRW workflow "online-cmaq" branch on Hera. Here is the error message 

ALL DAYS HERE
/scratch2/NCEPDEV/naqfc/Jianping.Huang/emissions/nexus/NEI2016v1/v2022-07/08/NEI2016v1_0.1x0.1_20160805_rwc.nc /scratch2/NCEPDEV/stmp3/Jianping.Huang/NCO_OUTPUT/tmp/nexus_emission.37330069/tmp_NEXUS/input/NEI2016v1/v2022-07/08/NEI2016v1_0.1x0.1_20190802_rwc.nc
/scratch2/NCEPDEV/naqfc/Jianping.Huang/aqm.v7.0.15/ush/bash_utils/print_msg.sh: line 216: BASH_SOURCE[1]: unbound variable
FATAL ERROR:
ERROR:
  From script:  ""
  Full path to script:  ""
Call to execute nexus standalone for the FV3LAM failed.
Exiting with nonzero status.
End exregional_nexus_emission.sh at Tue Nov  1 20:16:18 UTC 2022 with error code 1 (time elapsed: 00:01:03)

real    1m2.586s
user    0m0.919s
sys     0m2.128s
FATAL ERROR:
ERROR:

Details can be found at /scratch2/NCEPDEV/stmp3/Jianping.Huang/NCO_OUTPUT/output/20190801

@bbakernoaa @chan-hoo

**Comment by bbakernoaa** [comment]
@drbimbusrain can you take a look at this? Can you try the latest nexus_emission step for this date?

**Comment by JianpingHuang-NOAA** [comment]
@Chan-Hoo Jeon - NOAA Affiliate ***@***.***> @Barry Baker -
NOAA Federal ***@***.***>

If NEXUS_INPUT_DIR is pointed to
/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus, it works.
