### ISSUE TITLE
NEXUS generating extremely large value of emissions with the online-cmaq srw workflow

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#35]
I am testing the new workflow with UFS-AQM for the large domain run. However, I am seeing extremely large values of emissions (e.g., CO, ISOP) generated by NEXUS. 

Please check the emission file, aqm.t12z.NEXUS_Expt.nc
/scratch2/NCEPDEV/stmp3/Jianping.Huang/emc.para/com/aqm/v7.0/aqm.v7.0.c15.20190801/12  (Hera).

The model runs were completed successfully without any failure or warning but the results look weird. Please see O3 prediction for Slide 2

https://docs.google.com/presentation/d/1z_o1WET8mU590CREuWMWdjT1SUbziNXNDPxyLgn25w4/edit#slide=id.g16f20c7e4e2_0_5

Thanks.

Jianping

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA @BrianCurtis-NOAA Although I cannot see what exactly you are talking about from this plot. I can confirm that some values are being populated with non-null values in the [run_nco_combine_ant_bio.sh](https://github.com/noaa-oar-arl/NEXUS/blob/develop/utils/run_nco_combine_ant_bio.sh) script.  I have already asked @zmoon to work on fixing this script.  

@zmoon any updates?

**Comment by zmoon** [comment]
Working on it now.

**Comment by zmoon** [comment]
This was a masking issue, which I think we have resolved in https://github.com/noaa-oar-arl/NEXUS/pull/16 (also dropped ~ 90 s from run time).

**Comment by JianpingHuang-NOAA** [comment]
I just checked out the Online-CMAQ workflow and tested it. I still saw the same issue. What is the hash number for the updated NEXUS? Meanwhile, can you send the new hash number to Chan-Hoo for the WF update? 

Thanks,
Jianping

**Comment by zmoon** [comment]
@JianpingHuang-NOAA , seems it wasn't as fixed as I thought, but I have a new fix (https://github.com/noaa-oar-arl/NEXUS/pull/18) and then after we merge that I will provide the new hash.

Those high values we were seeing are the [default fill value](https://github.com/noaa-oar-arl/NEXUS/pull/16#issuecomment-1314232050) for the dtype though, so I suspect they might have been automatically masked or filled with something else on load in the model even though `_FillValue`/`missing_value` not set.

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA should this be closed?

**Comment by zmoon** [comment]
With https://github.com/ufs-community/ufs-srweather-app/pull/494 which updated NEXUS hash to include our fixes mentioned in this thread having been merged, I think this could be closed. But @JianpingHuang-NOAA can confirm.

**Comment by JianpingHuang-NOAA** [comment]
It is done.
