### ISSUE TITLE
FENGSHA not properly initialized

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-EMC/AQM#36]
Hi I noticed an issue taking a look at @JianpingHuang-NOAA run related to fengsha.  Essentially fengsha was not properly initialized so the model has not been running with fengsha in the RT tests nor the recent historical runs completed.  

fengsha needs to be included here: https://github.com/ufs-community/ufs-srweather-app/blob/online-cmaq/parm/aqm.rc#L32-L36 for it to properly be enabled.  Otherwise the fengsha_yn is never set and no input files from fengsha is read.  

I have completed a single day test by re-enabling fengsha through the workflow and a draft PR (https://github.com/ufs-community/ufs-srweather-app/pull/449) is already in place for the workflow.  But it did uncover another issue.  The input file for FENGSHA had the wrong dimensions compared to the current C793 domain causing a model crash.  I have generated new files and have completed a simulation showing that the model executed on wcoss2.  

The new input files can be found on WCOSS2 here: `/lfs/h2/emc/ptmp/barry.baker/FENGSHA_p8_10km_inputs_C793_AQM_13km.nc`
or on hera here: `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/FENGSHA/Online_CMAQ/FENGSHA_p8_10km_inputs_C793_AQM_13km.nc`

@zmoon

**Comment by JianpingHuang-NOAA** [comment]
Ok, this is new or not? I got continuous failures after I checked out the
online-cmaq workflow with the PM2.5 calculation code today which I did not
see in the past.  I am going back to test the ufs-model without pm2.5 code
and see whether it is ok. Thanks !

**Comment by zmoon** [comment]
@JianpingHuang-NOAA before, FENGSHA was just silently skipped so wouldn't have caused such issue. We discovered the input file issue only in ufs-community/ufs-srweather-app#449 after properly enabling FENGSHA.

**Comment by JianpingHuang-NOAA** [comment]
Yes, I agree.
I checked the aqm.rc file and location of input and its dimension
/lfs/h2/emc/physics/noscrub/jianping.huang/data/emissions/nexus/Dust/FENGSHA_p8_10km_inputs_AQM_NA_13km.nc,
and saw it

dimensions:

*   x = 768 ;        y = 528 ;*
        time = UNLIMITED ; // (12 currently)

However, the model does not fail and also not provide any warning message.
NCO does not want to see this.  If they find any issue like this, i.e.,
when any input files are missing or wrong but the model does not  provide
any warning, they will return the code to us.

Thanks for catching this.

**Comment by zmoon** [comment]
> However, the model does not fail and also not provide any warning message.

That is to be expected with current online-cmaq branch, because, although the EMC sample config has fengsha supposedly enabled, this wasn't reflected in the template aqm.rc `emission_sources` list, so fenghsa was never run [^a].

We have a bit more info on this in https://github.com/ufs-community/ufs-srweather-app/pull/449 . I understand that when @chan-hoo tested it with fengsha properly enabled, the model did indeed fail with the current input file setting.

[^a]: or at least, fengsha not considered as an emission source and the file was never read in the emis mod

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, if you checked out the workflow today, it won't work correctly. Please check out the hash `3ef50eb`. Sorry for any inconvenience. I'm trying to fix the issue now.

**Comment by BrianCurtis-NOAA** [comment]
I have a PR coming into UFSWM that will add the fengsha section to aqm.rc but will not add it to the emissions section because it seems to stop the model from running. I think this issue once addressed, we can enable fengsha in aqm.rc in the UFSWM.

I know that @JianpingHuang-NOAA has fengsha enabled in one of his workflows, but am surprised this issue never arose in his testing.

**Comment by bbakernoaa** [comment]
@BrianCurtis-NOAA The new input files fixes this issue for the C793 grid.  

> The new input files can be found on WCOSS2 here: /lfs/h2/emc/ptmp/barry.baker/FENGSHA_p8_10km_inputs_C793_AQM_13km.nc
or on hera here: /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/FENGSHA/Online_CMAQ/FENGSHA_p8_10km_inputs_C793_AQM_13km.nc

These files should be moved on wcoss to where the other inputs are.

I looked at @JianpingHuang-NOAA aqm.rc that he posted in the other issue, it did not enable fengsha completely. Although the emission block is there if it is not listed here: https://github.com/ufs-community/ufs-srweather-app/blob/online-cmaq/parm/aqm.rc#L32-L36 it will not be included in the model as that block is never read in and so it defaults to the original CMAQ dust scheme.

**Comment by HaixiaLiu-NOAA** [comment]
@bbakernoaa Has this issue been resolved? Do you have any test results demonstrating whether correctly enabling Fengsha has an impact? Thanks.

**Comment by bbakernoaa** [comment]
@HaixiaLiu-NOAA Yes this should be resolved with the new input file for the C793 domain as well as the workflow addition to properly add fengsha to the emission list https://github.com/ufs-community/ufs-srweather-app/pull/449

**Comment by bbakernoaa** [comment]
I'll close the issue

**Comment by JianpingHuang-NOAA** [comment]
Hi Barry,

We need to run a dust event and make sure that the code works properly.

Jianping

**Comment by bbakernoaa** [comment]
This was done at the time of merging.  There is no need to go back and rehash that in my
opinion.  Nothing with the scheme itself changed here.  Just an input file and correctly adding it to the workflow

**Comment by bbakernoaa** [comment]
i.e. there really isn't any code change here

**Comment by JianpingHuang-NOAA** [comment]
Good to know that. Just want to make sure everything is in the right place
before we do a long period of retro runs.

Thanks,

Jianping
