### ISSUE TITLE
AQM should run with a debug build of UFSWM

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [NOAA-EMC/AQM#44]
An NCO requirement is to run the UFSWM AQM with Debug build.

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA Should "ops implementation" be used to label this?

**Comment by BrianCurtis-NOAA** [comment]
The code fixing this issue was merged. Closing.

**Comment by BrianCurtis-NOAA** [comment]
Reopening this as the fix caused strange behaviors in AQM. Another approach will need to be used to complete a run in debug mode.
