### ISSUE TITLE
VGTOP3D needs to be in Pa not mb

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [NOAA-EMC/AQM#45]
## Describe issue
Small Fix:
https://github.com/BrianCurtis-NOAA/AQM/blob/50f7bd2560d39e15798226499ca84e555c05982c/src/shr/aqm_methods.F90#L211

VGTOP3D is provided in mb but needs to be in Pa
which means: 20 * 101.325

**Comment by zmoon** [comment]
>  which means: 20 * 101.325

Should that be 20 * 100?

**Comment by BrianCurtis-NOAA** [comment]
I think so, @rmontuoro do we need to keep the 1.325?

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA Should "ops implementation" be used to label this?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Should "ops implementation" be used to label this?

Yes, thank you.

**Comment by rmontuoro** [comment]
@zmoon  - CMAQ's variable naming and comments are misleading in this case. The conversion is actually between Pa and milliatmosphere. See here:

https://github.com/USEPA/CMAQ/blob/be5d28fd1b60522e6fc98aefeead20e6aac3530b/CCTM/src/phot/inline/SEAS_STRAT_O3_MIN.F#L2457

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA What is the status of this issue? Thank you.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA What is the status of this issue? Thank you.

This is a one-line small change that can go in at any time before code freeze. I was waiting for a PR to come in to AQM to add it to that, but can get a PR started if none seem imminent.

**Comment by BrianCurtis-NOAA** [comment]
This change is in the code being tested for point sources from Raffaele.

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA Can this issue be closed? Thanks

**Comment by BrianCurtis-NOAA** [comment]
It will be closed when PR #53 is merged.
