### ISSUE TITLE
Online-CMAQ seems to mis-predict an dust event on Dec. 2, 2022 at 06z cycle

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#47]
@bbakernoaa 

## Description:
The near real time run NCRT22 uses the ARL point source code (hash #: [5cf99ae](https://github.com/noaa-oar-arl/AQM/commit/5cf99ae2461dfe4374e04a86d99f66dae2b53937)) and ufs-weather-model (3a8533c), and SRW-WF (EC[64d07e5](https://github.com/JianpingHuang-NOAA/ufs-srweather-app/commit/64d07e547f9d10cd500d31e2f71eda1354fb4157). 

As seen on EMC NRT run website (https://www.emc.ncep.noaa.gov/mmb/hchuang/web/html/rrfs_cmaq_pm25.html#picture) (maintained by Ho-Chun),

Please see the figure below for panel selection

![image](https://user-images.githubusercontent.com/54634403/205940828-69a83ccd-adf5-4210-988b-3a190fe61d42.png)

As compared to the operational forecast, the NRCT22 did not capture the dust event near Colorado and Kansas on Dec. 2 at the 17th forecast hour.

The aqm.rc file can be found at [here](https://github.com/JianpingHuang-NOAA/ufs-srweather-app/blob/NRTC22/parm/aqm.rc)  or the run dir is on Cactus at /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/run_fcst.id_1670042105_2022120206

It is clear that the Fengsha was included in the aqm.rc file
emission_sources: anthro fire fengsha

Please let me know if you need more information.

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA Before we label this a `bug` let's first figure out what is going on.  We don't know exactly what happened. RRFS-SD (which uses the same FENGSHA inputs but at a higher resolution) and uses the same algorithm) picked up this event and shows several other sources.  We should actually see two plumes the weather front shown here but also another event blowing from southeast 
![Screenshot 2022-12-06 at 10 00 02 AM](https://user-images.githubusercontent.com/22104759/205948128-8c2ae2c5-f108-4920-a640-ae39e7bc86eb.png)


Do we have a plot of `asoil`? this would be a good marker to see if there is a signal.  Perhaps the alpha parameter just needs tuned.

**Comment by bbakernoaa** [comment]
Also do we have a plot of the `surface wind speed` (10m) or `u*` ? This could be very valuable to see if it is an algorithm issue, bug or that the MET failed to predict the necessary conditions to get an event.

**Comment by JianpingHuang-NOAA** [comment]
Forget "bug" for the issue description. This is a new requirement that we
have to select (bug or new feature) when we open a new issue.

Since both the operational model and the online-CMAQ use the same code,
Fengsha, and their resolutions are similar. Of course the
meteorological fields may have some differences, but I do not expect they
will be very large. My concern is whether the settings with the Online-CMAQ
are correct. Hope that we did not miss or mismatch anything.

Here is a quick screenshot for friction velocity

[image: image.png]

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA I can't see the image you tried to attach.

My point with RRFS-SD picking up the event is that it is the same algorithm and inputs more or less.

**Comment by JianpingHuang-NOAA** [comment]
![image](https://user-images.githubusercontent.com/54634403/205960802-5964eb9e-1c6a-42d4-bfb8-160dc39d04aa.png)

**Comment by bbakernoaa** [comment]
once cactus comes back up I'll try to simulate this day and figure out what is happening

**Comment by JianpingHuang-NOAA** [comment]
Ok, thanks.

**Comment by HaixiaLiu-NOAA** [comment]
@bbakernoaa have you made any update on this issue? Thank you very much.

**Comment by HaixiaLiu-NOAA** [comment]
@bbakernoaa have you got a chance to investigate this Fengsha dust simulation? Could you please provide an update on your finding? Jianping is getting ready to perform a retro run with final AQMv7 setups.

**Comment by bbakernoaa** [comment]
@HaixiaLiu-NOAA I'm working on it

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA @rmontuoro @HaixiaLiu-NOAA @BrianCurtis-NOAA I have been working on this.  I ran into a few issues getting things running with cactus going up and down but from what I can tell the latest develop branch of the ufs-weather-model reproduced the results pretty nicely.  To reproduce these are the steps that I took:

- checkout latest workflow: git clone -b online-cmaq https://github.com/ufs-community/ufs-srweather-app
- modify External.cfg to point to the develop branch of the ufs-weather-model (the hash was a few commits behind and didn't include several of the latest updates) 
- create a config.yaml for 2022-12-02 starting at 12z: you can see it here `/scratch2/NAGAPE/arl/Barry.Baker/workflows/cmaqdev/ush/config.yaml`
- modify the `parm/aqm.rc` file to increase alpha (to boost dust emissions just to see if the model is reproducing the location correctly [ it is ] ) 
```bash 
#
# FENGSHA
#
fengsha_yn: {{ do_aqm_fengsha | lower }}
fengsha_type: fengsha
fengsha_format: netcdf
fengsha_file: {{ aqm_rc_fengsha_file_fp }}
fengsha_frequency: monthly
fengsha_alpha: 1
fengsha_species::
    CLAYF       1.00000   clayfrac     1
    SANDF       1.00000   sandfrac     1
    DRAG        1.00000   albedo_drag  1
    UTHR        1.00000   uthres       1
::
```

Having done this I ran a 24 hour simulation and plotted the maximum PM10 value.  You can clearly see the event was picked up and produced extrodinary dust (which is should have as I artificially increased the emission strength (getting scaling now)) 

![image](https://user-images.githubusercontent.com/22104759/207136319-4476b628-3f62-426a-9229-dbcb9586c356.png)


Results can be found here: `/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/aqm.v7.0.c7/2022120212`

**Comment by JianpingHuang-NOAA** [comment]
@Barry Baker - NOAA Federal ***@***.***>  Thanks for the update.
Is there any change for the code or just increase the alpha value from 0.05
to 1?

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA I do not recommend increasing the alpha parameter to 1.  Let me perform some more testing.  With increasing to 1 we were seeing PM10 concentrations of > 20,000 ug/m3.  This is a little extreme even for a huge dust event.  

No code changes other than using the head of develop as noted above

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA Ive started a draft PR for the workflow to correct the aqm.rc (above) with the correct value for dust_alpha.  It raises it from 0.05 to 15. (this is approximately 1000x or the unit conversion from kg -> g) but it puts it on the correct scale. I also updated the aqm.rc to reflect the recent changes in the AQM component in the develop branch. This also brings it consistent with the RTs (@BrianCurtis-NOAA)  I was able to reproduce the Dec 2nd event as well as the Dec 12th event with reasonable concentrations for PM2.5 and PM10.  Will update more with plots later.

**Comment by JianpingHuang-NOAA** [comment]
@bbakernoaa While I test Raffaele's point-source code, I did change dust_alpha value from 0.05 to 15 as you suggested.  However , it seems too strong based on very preliminary analysis. Here is the asoil simulation on Sept. 5, 2020 (with cold start from Sept. 2, 2020)

![image](https://user-images.githubusercontent.com/54634403/208704328-cc9750eb-0538-45b8-bd62-ce7a2a3985f2.png)

**Comment by bbakernoaa** [comment]
PM10 concentrations > 1000 are to be expected (which is what ASOIL is). Can you send me the location?

**Comment by JianpingHuang-NOAA** [comment]
The run dir can be found on Cactus 

/lfs/h2/emc/aqmtemp/para/tmp/run_fcst.id_1671534874_2020090512

Where you can find my aqm.rc file 

The model output files are available at /lfs/h2/emc/aqmtemp/para/com/aqm/v7.0/c29.20200905/12

**Comment by JianpingHuang-NOAA** [comment]
Sure, here it is.

https://github.com/NOAA-EMC/AQM/issues/47

**Comment by JianpingHuang-NOAA** [comment]
Here is PM2.5 prediction at the 7th forecast hour on Sept. 5, 2020 (with cold start from Sept. 2). 

![image](https://user-images.githubusercontent.com/54634403/208706340-cc8ee4e8-dafb-45d2-98cd-3ea9f15c8a2b.png)

The major contributor to PM2.5 is asoil. I am not sure this is a real dust event,  especially the location of event.

**Comment by bbakernoaa** [comment]
We saw something similar to this in RRFS but we haven't seen this in the global model.  Though the global model is at 25km so maybe that is the issue.  I'll do some tests fixing the dust inputs like I did in RRFS and we can go from there.

**Comment by bbakernoaa** [comment]
this will not require a code change.  Only an input file change for dust

**Comment by bbakernoaa** [comment]
This has been fixed and we should close this now.  just needed to update the alpha value to something larger.

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA can you close this one? Thanks

**Comment by JianpingHuang-NOAA** [comment]
Yes.
