### ISSUE TITLE
Varying forecast length is required for the SRW workflow to support Online-CMAQ retro runs

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#49]
## Description @chan-hoo 
AQM runs 72-hr forecasts for 06z and 12z cycles and 06-hr forecasts for 00z and 18z cycles. However the current SRW workflow uses a constant forecast length (i.e., FCST_LEN_HRS in config.yaml) for all  the cycles. It will save a lot of computer resources (computing and storage) for retro runs if the SRW WF is allowed to do multiple day simulation with a varying forecast lengths for different cycles. 

Thanks

**Comment by HaixiaLiu-NOAA** [comment]
@Chan-Hoo, could you please take a look at this issue and provide an estimated time for completing this task? Thank you. AQM retro runs need this capacity.

**Comment by chan-hoo** [comment]
@HaixiaLiu-NOAA, I just started working on the restart capability issue. I am not sure how long it will take at this moment. I don't have any good idea for this now, but it looks quite complicated. Once it is complete, I'll look into this.

**Comment by chan-hoo** [comment]
@HaixiaLiu-NOAA @JianpingHuang-NOAA, the capability is ready for use in the workflow. As you can see in the sample script ('/ush/sample_config/EMC_run/config.yaml_nco_aqmna13km_1day_wcoss2'), you should set `FCST_LEN_HRS` and `FCST_LEN_CYCL` as follows:
```
FCST_LEN_HRS: -1
FCST_LEN_CYCL:
  - 6
  - 72
  - 72
  - 6
 ```
 This pattern will be recurred for all cycle dates in the 'setup.py' script.
 As there is a critical structural issue in the workflow XML file, the `run_post` task is not available with this option. The parameter `RUN_TASK_RUN_POST` should be set to `false`.
