### ISSUE TITLE
 nexus_gfs_sfc failed with the latest workflow

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#51]
## Description:
@chan-hoo @bbakernoaa 

I am using the latest workflow to test the bias correction code in our NRT. T  Below is the information about the online-cmaq workflow

commit ccac0b40994da6b15ac913ff7267771672b15090
Author: chan-hoo <chan-hoo.jeon@clogin03.cactus.wcoss2.ncep.noaa.gov>
Date:   Sun Dec 18 15:01:54 2022 +0000

However, I got a failure with the nexus_gfs_sfc job.  The details can be found on Cactus

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20221219 > vim nexus_gfs_sfc_2022121900.id_1671457448.log.0

Is this task used to replace MERR2 with GFS data to support biogenic emission calculation?

Can you take a look at the run log file?

Thanks

Jianping

**Comment by bbakernoaa** [comment]
@chan-hoo we really need to put these in a separate branch/fork before committing directly to the `online-cmaq` branch in the authoritative repository

@JianpingHuang-NOAA This is going to be a new feature you may want to roll back to last Friday

**Comment by chan-hoo** [comment]
This task works well on my end.

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA Yes this is to support the GFS driven biogenics.

I quickly looked at this and it appears that the GFS data isn't archived yet.

```bash
[hpsscore1]/NCEPDEV->cd /NCEPPROD/hpssprod/runhistory/rh2022/202212/20221219
[hpsscore1]/NCEPPROD.../rh2022/202212/20221219->ls
/NCEPPROD/hpssprod/runhistory/rh2022/202212/20221219:
dcom_decoder_logs.tar       dcom_decoder_logs.tar.idx   packages.update.tar         packages.update.tar.idx
```

@chan-hoo Do we have the option to look on local disk to see if that is available?

**Comment by chan-hoo** [comment]
I've added a 'local directory' option to `NEXUS_GFS_SFC`. If the sfc files exist in `COMINgfs_BASEDIR`, they will be copied from it. Otherwise, the files are retrieved from HPSS.

**Comment by bbakernoaa** [comment]
@chan-hoo perfect! I have integrated the changes into the workflow and am running a test right now.  Currently there is minor differences between MERRA2 driven and GFS driven but there are differences.  I'm really encouraged that this is going to be smooth sailing.  Once I'm confident in the changes I'll create a PR for the workflow. 

You can find the differences on WCOSS2 here: `/lfs/h2/emc/lam/noscrub/barry.baker/workflow/srwdev/scripts/exregional_nexus_emission.sh`

@JianpingHuang-NOAA Please do not try to start a new run with this yet.  The tests are still ongoing.

**Comment by bbakernoaa** [comment]
This is fixed.  Should close @BrianCurtis-NOAA

**Comment by BrianCurtis-NOAA** [comment]
> This is fixed. Should close @BrianCurtis-NOAA

10-4
