### ISSUE TITLE
the ufs-aqm forecast run failed on January 9th at 12z cycle

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#54]
Both Kai and I met the same error when we ran the forecast model for January 9th at 12z cycle. The run stopped at the very beginning. The PET ESMF log file shows the code failed to update emissions

20230109 232247.934 ERROR            PET0000 aqmio.F90:1839  - Error reading field ACET from NetCDF data set (strerr=NetCDF: HDF error, ncerrToCheck=-101)
20230109 232247.934 ERROR            PET0000 aqm_emis_mod.F90:1458  - Passing error in return code
20230109 232247.934 ERROR            PET0000 aqm_comp_mod.F90:197  - Failed to update emissions

. Meanwhile, the NEXUS ran successfully. 

The details can be found from the the following PET ESMF log file.

/lfs/h2/emc/aqmtemp/para/tmp/run_fcst.id_1673303943_2022010912/PET0000.ESMF_LogFile  (Cactus)

Can you take a look? @bbakernoaa 

Thanks,

**Comment by bbakernoaa** [comment]
I don't think I'm running into this issue.  You can see my results here: 

/lfs/h2/emc/stmp/barry.baker/expt_dirs/test0109

**Comment by JianpingHuang-NOAA** [comment]
Hi  Barry,

It is a retro run for Jan 9, 2022, not 2023.

Thanks for your quick response,

Jianping

**Comment by JianpingHuang-NOAA** [comment]
The failure was caused by pt-input file for at 12z on Jan. 9, 2022. The issue was fixed after regenerating pt-input file
