### ISSUE TITLE
ufs_aqm forecast run failed at 18z on 20220916: Overflow with infinity 

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#55]
The retro run failed at 18z on 20220916 with the following error message 

FATAL from PE  1669: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
FATAL from PE   163: Overflow in mpp_reproducing_sum(_2d) conversion of      Infinity
FATAL from PE   643: Overflow in mpp_reproducing_sum(_2d) conversion of      Infinity
FATAL from PE   772: Overflow in mpp_reproducing_sum(_2d) conversion of      Infinity
FATAL from PE  1169: Overflow in mpp_reproducing_sum(_2d) conversion of      Infinity
...
The details can be found from 
/lfs/h2/emc/physics/noscrub/jianping.huang/NRT_test/run_fcst.id_1673899796_2022091618 > vim errfile 

We need to figure it out what input files cause this issue, emission files or  ...

**Comment by JianpingHuang-NOAA** [comment]
I enabled the capability of writing the PET*ESMF_LogFile files now.

All the PET Log files are available on Cactus

/lfs/h2/emc/aqmtemp/para/tmp/run_fcst.id_1673899796_2022091618

**Comment by bbakernoaa** [comment]
Quickly looked at this.  Seems to be the `INPUT/gfs_data.nc` 

The some of the variables are `> 10^+36`

**Comment by JianpingHuang-NOAA** [comment]
Thanks Barry for narrowing down the issue.  It seems that the previous cycle run got some mix up issues and I am going to rerun the simulation for the previous cycle (12z) ...
