### ISSUE TITLE
Long run time to prepare input file(s) for PT code with the recent online-cmaq SRW workflow

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#59]
The recent WF is able to prepare input files for the PT code, but it takes more than 45 minutes to generate an input file for a run with 72 forecast hours, which is too log for us.

Can you help us to optimize the python-based code?  @bbakernoaa 

Tracking NOAA-EMC/AQM-utils/pull/4

**Comment by bbakernoaa** [comment]
just to note that this isn't a new issue it was already there with the workflow beforehand

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, this is not a 'bug'. Please change the label (maybe 'feature' if it exists)

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo You are right

**Comment by bbakernoaa** [comment]
@zmoon can you take a look at this?

**Comment by BrianCurtis-NOAA** [comment]
I will add this to the AQM v8 project. If you feel it needs to be in AQM v7 let me know, or if you feel it doesn't need to be a part of what will become AQM v8, also let me know. Thanks.

**Comment by bbakernoaa** [comment]
@BrianCurtis-NOAA This is just something that may be an issue for NCO with the long runtime and no restart capability for this step.  

I think @zmoon has been working on this and is close to getting a solution. https://github.com/NOAA-EMC/AQM-utils/pull/4 

Note that this isn't a science change just a runtime issue.

**Comment by BrianCurtis-NOAA** [comment]
@bbakernoaa Do you feel this will make it in time for code delivery?

**Comment by bbakernoaa** [comment]
I believe it should be ready by the end of the week.  @zmoon How close is this?

**Comment by BrianCurtis-NOAA** [comment]
Great. I'll track it with v7. Thanks.

**Comment by zmoon** [comment]
> I believe it should be ready by the end of the week. @zmoon How close is this?

Yeah it is essentially ready, I can finish the cleanup by the end of the week for sure. We just have to decide where to place the new data files.

**Comment by bbakernoaa** [comment]
@zmoon lets put them in the official location.  @BrianCurtis-NOAA @JianpingHuang-NOAA  can you help to make sure that they get put where the rest of the emission files are going.

@zmoon we will keep another copy in the ARL data directory - On hera: `/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/NEI2016v1/v2023-01-PT`

**Comment by zmoon** [comment]
The data have been copied to
```
/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/NEI2016v1/v2023-01-PT
```

**Comment by bbakernoaa** [comment]
I believe this is finished.  Lets close it

**Comment by JianpingHuang-NOAA** [comment]
Ok.
