### ISSUE TITLE
Bugzilla - Bug 1275 for AQMv6 needs to be addressed for AQM v7 implementation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#72]
@BrianCurtis-NOAA @chan-hoo 

This is the bug 1275 created by NCO during the AQM v6 implementation.  We are required to address this issue before we deliver AQM v7 code to NCO.

The detail about bug 1275 can be found from the following link

http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi

Once you create your account and log in and do a search on AQM, you will find it.

I copied the detail below for your refernce.

=====================================
[Samy Kamal](mailto:samy.kamal@noaa.gov) 2021-07-02 12:09:45 UTC
Please make sure to use the most recent compilers and libraries available on wcoss. 
For example, the current list of modules loaded includes:
export intel_ver="15.0.3.187"----->(6 years old)
export grib_util_ver="1.0.3"   -----> (5 years old version of grib)
export grib_util_5_ver="1.0.5" ------->(a newer version of grib used at the same time)

If you have problems using the software installed in production, please bring that to our attention as soon as possible, we can work on it together to ensure smooth implementation.
Thank you
======================================

Please make sure our AQMv7 does not have such an issue. 

Thanks,

Jianping

**Comment by BrianCurtis-NOAA** [comment]
I'm confused. Do we have to fix AQMv6 before implementing AQM.v7?

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA There are newer versions of the intel compiler available on WCOSS2, but the version in https://github.com/ufs-community/ufs-srweather-app/blob/develop/versions/build.ver.wcoss2 of 19.x... is still a supported intel compiler version on WCOSS2. I don't think we need to adjust/test a newer version, but I don't know for certain.

**Comment by JianpingHuang-NOAA** [comment]
@BrianCurtis-NOAA  Thanks. I am closing the ticket.
