### ISSUE TITLE
Bug 1276 for AQMv6 needs to be addressed to support AQM v7 implementaion

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#73]
@bbakernoaa @ytangnoaa

This bug is related to aqm_fv3chem_L35.sh for AQMv6 implementation. We need to address it and make sure that we do not have a similar issue for AQM v7 implementation.

I am copying the message from NCO bugzilla below
=========================================================
[Samy Kamal](mailto:samy.kamal@noaa.gov) 2021-07-06 10:48:23 UTC
There is a hard-coded email to [SABSupervisor@noaa.giv](mailto:SABSupervisor@noaa.giv) in "ush/aqm_fv3chem_L35.sh".

Please remove the hard-coded email and use maillist variable defined in the .version file.

Example:
ush/aqm_fv3chem_L35.sh:         echo "~s ${lbc_cyc} GEFS output for ${cycle} CMAQ run are missing ${lbccyc} output are used CMAQ RUN SOFT FAILED" | mail [SABSupervisor@noaa.gov](mailto:SABSupervisor@noaa.gov)
ush/aqm_fv3chem_L35.sh:         echo "~s Both ${lbc_cyc} and ${lbccyc} GEFS output for ${cycle} CMAQ run are missing. CMAQ RUN SOFT FAILED" | mail [SABSupervisor@noaa.gov](mailto:SABSupervisor@noaa.gov)
Thank you
Samy
===================================================== 

Thanks,

Jianping

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo @ytangnoaa @RaghuReddy-NOAA 

Hi Matt and Chan-Hoo,

Can you help us to review Lines 159-167 in exregional_aqm_lbcs.sh at  /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.47/scripts > vim exregional_aqm_lbcs.sh

, and make sure that our script with AQMv7 is able to address NCO bugzilla 1276 for AQMv6 created by NCO

http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1276

Thanks,

Jianping

**Comment by JianpingHuang-NOAA** [comment]
@MatthewPyle-NOAA 

Hi Matt,

I am including you now in case you have a suggestion on our bugzilla for AQMv6.

Jianping

**Comment by MatthewPyle-NOAA** [comment]
@JianpingHuang-NOAA it seems like the Bugzilla is specifically about a hard coded e-mail address.  In the new scripts I don't see any e-mails sent for missing data, making this bugzilla item resolved by the updated system.  Do you see it differently?

**Comment by JianpingHuang-NOAA** [comment]
@MatthewPyle-NOAA @ChrisMacIntosh-NOAA 

I have added a new line (line124)
  echo "~s ${chem_lbcs_fp} GEFS output for ${cycle} CMAQ run are missing output are used CMAQ RUN SOFT FAILED" | mail.py $maillist

 in the script, 
/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.46/scripts/exregional_aqm_lbcs.sh

and add one more line 
export maillist=SABSupervisor@noaa.gov
in the script, run.ver 
/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.46/versions

I believe that is something that NCO wants  to have.

Chan-Hoo,

Please review the  changes I made and then merge them into the workflow.

In addition, we need to add similar information for fire emission script 
/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.46/scripts > exregional_fire_emission.sh  @KaiWang-NOAA 

For both AQM LBCs and fire emissions, we need to keep the model be running but need to report the warning message to SABSupervisor through maillist which is defined in run.ver.

Thanks,

Jianping

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, If you intend to add it for GEFS file, the first location is not correct. I put the following for GEFS file:
- exregional_aqm_lbc.sh:
```
if [ "${RUN_ENVIR}" = "nco" ] && [ ! -z "${maillist}" ]; then
  echo "${AQM_MOFILE_FHR_FP} GEFS output for ${cycle} run is missing. AQM RUN SOFT FAILED" | mail.py $maillist
fi
```
- exregional_fire_emission.sh:
```
if [ "${RUN_ENVIR}" = "nco" ] && [ ! -z "${maillist}" ]; then
  echo "${AQM_FIRE_DIR}/${CDATE_md1} fire emission raw data for ${cycle} run is missing. AQM RUN SOFT FAILED" | mail.py $maillist
fi
```

**Comment by JianpingHuang-NOAA** [comment]
resolved
