### ISSUE TITLE
Bug 1280 for AQMv6 needs to be addressed by AQMv7 implmentation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#74]
@BrianCurtis-NOAA @chan-hoo 

This bug is related to AQMv6 implementation but we need to address it and make sure that we do not have a similar issue for AQMv7.

The issue can be found from the following link
http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1280

And I copy it below for your reference 
------------------------------------------------------------------------------------
[Samy Kamal](mailto:samy.kamal@noaa.gov) 2021-07-15 11:00:06 UTC
Right now, The makefiles for the model components only have "install" and "clean" targets.
Please add debug target to all makefiles.
Also please make sure all targets(install, debug, and clean) can be used from the build_cmaq.scr script.
--------------------------------------------------------------------------------------------------

Thanks,

Jianping

**Comment by BrianCurtis-NOAA** [comment]
We use CMake now and it has -DDEBUG option which is also tested in a regression test. NCO can build with -DDEBUG=ON and get a debug build. I think you can close this.

**Comment by JianpingHuang-NOAA** [comment]
Thanks !
