### ISSUE TITLE
Bug 1281 of AQMv6 needs to addressed by AQMv7 implementation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#75]
@BrianCurtis-NOAA @chan-hoo 

This is another bug related to AQMv6 implementation and needs to be addressed before we deliver the code 

-----------------------
[Samy Kamal](mailto:samy.kamal@noaa.gov) 2021-07-15 14:54:50 UTC
Please make the code more easily scalable.
Right now forecast jobs do not run any faster with more nodes and crashes with less. 
This, if not fixed, will hinder any future expansions in the size of the model domain and/or temporal and spatial resolutions. 
It also makes it impossible to run the model on a faster schedule if needed.
--------------------------------------------

I am not sure that we have a similar issue or not. Do you have any suggestion on this?

Jianping

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA  @chan-hoo this is scalability testing (more MPI tasks = faster, less MPI tasks = slower). Has this been performed on AQM.v7 yet?

**Comment by JianpingHuang-NOAA** [comment]
I did increase the total task number from 1792 to 3582, and saw some improvement of runtime but not much.

**Comment by BrianCurtis-NOAA** [comment]
I believe that satisfies the upward scalability. Have you tested if the lowering of # MPI tasks slows down the model as anticipated, or crashes?

**Comment by JianpingHuang-NOAA** [comment]
I did in the past. It slowed down the forecast model running time

**Comment by BrianCurtis-NOAA** [comment]
OK. It's up to you to run a current test for scalability (recommended), but it seems like you've met the requirements from this bugzilla.

**Comment by JianpingHuang-NOAA** [comment]
Yes.

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA can this be closed?
