### ISSUE TITLE
NEXUS jobs failed with the updated workflow

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#79]
@chan-hoo @bbakernoaa 

The NEXUS jobs failed when I tested the latest SRW regional workflow on Cactus.

The run log files can be found on Cactus

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20230401 > vim  nexus_emission_2023040118_s02.id_1681946668.log.0

Can you take a look?

Thanks,

Jianping

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I think it is because there exist two types of data in your tmp directory (`t00z` and `t18z`): 
```
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_gfs_sfc.2023041900

nexus_gfs_sfc.2023041900] ls
gfs.t00z.sfcanl.nc   gfs.t00z.sfcf003.nc  gfs.t18z.sfcanl.nc   gfs.t18z.sfcf003.nc  ncepdate
gfs.t00z.sfcf000.nc  gfs.t00z.sfcf006.nc  gfs.t18z.sfcf000.nc  gfs.t18z.sfcf006.nc  PDY
```
Please remove the `t00z` data files and try it again.
In my test run, it worked well.
```
202304190000       nexus_emission_00                    56028021           SUCCEEDED                   0         1         217.0
202304190000       nexus_emission_01                    56028022           SUCCEEDED                   0         1         205.0
202304190000       nexus_emission_02                    56028023           SUCCEEDED                   0         1         203.0
202304190000       nexus_emission_03                    56028028           SUCCEEDED                   0         1         213.0
202304190000       nexus_emission_04                    56028024           SUCCEEDED                   0         1         201.0
202304190000       nexus_emission_05                    56028025           SUCCEEDED                   0         1         200.0
202304190000        nexus_post_split                    56028659             RUNNING                   -         0           0.0
```

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, besides, the nexus_post_split task may fail in your version. It requires 'netcdf' on Cactus. I've updated the production branch. Please run 'git pull' in the home directory.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  The NEXUS still failed when I tested a retro run on 20230401 at 00z. The gfs_sfc data files were saved at 

/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_gfs_sfc.2023040100/gfs.20230331/18/atmos

rather than /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_gfs_sfc.2023040100/

If I linked those gfs_gfs files to /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_gfs_sfc.2023040100, it worked well.

You need to fix the issue for the retro runs.

Thanks,

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, updated. please run 'git pull' and test it again.

**Comment by JianpingHuang-NOAA** [comment]
It works now. I am closing the ticket for NEXUS.
