### ISSUE TITLE
Degrading performance of NRT O3 predictions in April, 2023

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#80]
Ho-Chun noticed that the NRT O3 predictions became worse starting from April, 2023 as compared its performance in the previous months and its counterpart, operational forecasts in April. 

Below is a comparison of hourly o3 over the eastern US in April.

![image](https://user-images.githubusercontent.com/54634403/233414156-e164153e-ffb7-4b31-9ed5-7ab28d7b8509.png)

This happened when the Dev machine was switched from Cactus to Dogwood and the number of splitting NEXUS jobs increased from 3 to 6. 

I am going to rerun the simulations for April 1-19, 2023 with several tests.

Jianping

**Comment by bbakernoaa** [comment]
Is this complete since AQMv7 was transitioned?

**Comment by JianpingHuang-NOAA** [comment]
@Ho-ChunHuang-NOAA  Can you confirm this ?

**Comment by Ho-ChunHuang-NOAA** [comment]
This is for v70c55 version that was running as NRT back in 2023.  Later we did not re-visit the April 2023 performance after we move to v7.0.8.

**Comment by bbakernoaa** [comment]
ok then we should close this as it is for an older version. Once its revisited lets reopen it

**Comment by JianpingHuang-NOAA** [comment]
@Ho-ChunHuang-NOAA  Is it possible to evaluate AQMv7.0.8 performance ?

**Comment by JianpingHuang-NOAA** [comment]
We close it now and will re-evaluate with AQMv7.0.8 and AQMv8.0

**Comment by Ho-ChunHuang-NOAA** [comment]
I checked, we do not have v708 output in April 2023.  So we can not re-do verification in April 2023.
