### ISSUE TITLE
Bias correction jobs failed for the retro runs and the scripts doe not follow NCO implementation standards

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#81]
@KaiWang-NOAA @chan-hoo  

I am testing the latest workflow for the bias correction. Here the bias correction is still based on bufr input data files.  Bias correction jobs for both O3 and PM2.5 failed for the retro runs, but they work well for the real-time. 

The bc run log files for 20230401 at 00z cycle can be found from

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20230401
 bias_correction_o3_2023040100.id_1682078897.log.0
 bias_correction_pm25_2023040100.id_1682078897.log.0

In addition, the bias correction scripts with ~/jobs and ~/scripts do not meet NCO implementation standards. We need to follow the current operational one, i.e., AQMv6 (/lfs/h1/ops/prod/packages/aqm.v6.1.7/jobs   and /lfs/h1/ops/prod/packages/aqm.v6.1.7/scripts) to modify them.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, please describe in detail which part does not meet the standard, or open a PR to the production branch. Then I'll review it

**Comment by bbakernoaa** [comment]
This should likely be closed too

**Comment by JianpingHuang-NOAA** [comment]
Yes, thanks
