### ISSUE TITLE
Missing two GFS surface input files for the job, JREGIONAL_NEXUS_GFS_SFC at 06z and 12z cycles

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#87]
Another issue has arisen for the NEXUS jobs related to biogenic emission calculations when we use the previous GFS surface inputs in the real-time runs. Specifically, we have identified that two files are missing: gfs.t${cyc}z.sfcf075.nc and gfs.t${cyc}z.sfcf078.nc for 06z and 1z cycles. 

These files are necessary for the job 'EGIONAL_NEXUS_GFS_SFC' which prepares GFS surface input files for biogenic emission calculations. For example, as of today's 12z cycle, this issue can be observed at the following location: 

/lfs/h2/emc/pt"mp/jianping.huang/emc.para/tmp/nexus_emission_02.57654133.cbqs01/GFS_SFC.

After that,  we need to modify the JREGIONAL_NEXUS_EMISSION related ex-script, exregional_nexus_emission.sh to include 78 hour gfs surface input data in the GFS_SFC_MEGAN_INPUT.nc

Please see an example at 
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_02.57654133.cbqs01/GFS_SFC_MEGAN_INPUT.nc

@chan-hoo @bbakernoaa @lgannoaa

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, please open an issue on the workflow to the UFS SRW App repo directly (https://github.com/ufs-community/ufs-srweather-app/issues). Please do not post it on `NOAA-EMC/AQM`. In addition, if you resolved the issue, please submit a PR to the `production/AQM.v7` branch. I will not receive any email requests for updating the workflow any more. Please use "Issues" and "Pull requests (PR)" on the UFS SRW App github repository.

**Comment by JianpingHuang-NOAA** [comment]
@Chan-Hoo Jeon - NOAA Affiliate ***@***.***>  Sure. I will
create all the workflow-related issues through the UFS SRW App.  I will not
work on resolving those issues, but I will help to test any change with the
workflow.

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA is this completed?

**Comment by JianpingHuang-NOAA** [comment]
Completed
