### ISSUE TITLE
Code compilation warning issues to support AQMv7 implementation 

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#93]
@BrianCurtis-NOAA @rmontuoro

The AQMv7 package was returned due  to the violation of EE2 compliance.  Code compilation warnings are the part of the reasons. 

For AQM, we are still seeing the following warnings.

1) ~/sorc/ufs-weather-model/AQM/src/io/ioapi

/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/io/ioapi/m3utilio.F90(198): warning #6843: A dummy argument with an e
xplicit INTENT(OUT) declaration is not given an explicit value.   [BUFFER]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/io/ioapi/m3utilio.F90(183): warning #6843: A dummy argument with an e
xplicit INTENT(OUT) declaration is not given an explicit value.   

2)  ~/src/model/CMAQ/CCTM/src/STENEX/noop
[BUFFER]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(162): warning
 #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(141): warning
 #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(129): warning
 #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(106): warning
 #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(84): warning 
#6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88c/sorc/ufs-weather-model/AQM/src/model/CMAQ/CCTM/src/STENEX/noop/noop_data_copy_module.f(61): warning 
#6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DATA2]

===================
The code was checked out from https://github.com/ufs-community/ufs-weather-model
hash= 4cf17f7

**Comment by rmontuoro** [comment]
@JianpingHuang-NOAA and @BrianCurtis-NOAA - PR #94 removes all build warnings and compiler remarks.

**Comment by bbakernoaa** [comment]
If this is merged should we close it?

**Comment by JianpingHuang-NOAA** [comment]
Yes.

**Comment by JianpingHuang-NOAA** [comment]
It is closed now. Thanks
