### ISSUE TITLE
Reproducibility of chemical fields with different layout values for AQMV7 

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#97]
## Description:

During the scaling tests with the AQMv7, it is noticed that all meteorological fields are reproducible with different layout values but the all chemical fields are not.  The issue disappears if we turn off point-source emissions. This is likely due to the algorithm that used to map point sources to grids which is done for each tile.

**Comment by JianpingHuang-NOAA** [comment]
Please follow this table ([here](https://docs.google.com/presentation/d/1ySapWlm-bvsDj3UqPF7Ux5KwNSB0eagtiCQx457Y0Ws/edit#slide=id.g26b6bf00de2_0_0)) to modify layout_x, layout_y and other related parameters, you will see the difference in chemical fields in the dyn files.

**Comment by bbakernoaa** [comment]
was this completed?

**Comment by JianpingHuang-NOAA** [comment]
This has been fixed in the AQMv7.0.8 code.

**Comment by JianpingHuang-NOAA** [comment]
It has been fixed in the AQMv7.0.8 code. The issue is closed now.

**Comment by JianpingHuang-NOAA** [comment]
But we need to do a similar test for the AQMv8.0 code later.
